POST {{$dotenv host}}/products
Content-Type: application/json

{
  "name": "Product#1",
  "desc": "Product#1 Desc",
  "price": 2000,
  "categoryIds": [1, 2]
}

###

PATCH {{$dotenv host}}/products/99
Content-Type: application/json

{
  "name": "Product-1"
}

###

GET {{$dotenv host}}/products?page=3&limit=5


###

GET {{$dotenv host}}/products/aestas

###

DELETE {{$dotenv host}}/products/99

###

GET {{$dotenv host}}/categories

###

GET {{$dotenv host}}/categories/1

###

POST {{$dotenv host}}/categories
Content-Type: application/json

{
  "name": "MyCat",
  "desc": "MyCat-Desc"
}

###

PATCH {{$dotenv host}}/categories/21
Content-Type: application/json

{
  "name": "MyCat21",
  "desc": "MyCat-Desc21"
}

###

DELETE {{$dotenv host}}/categories/21