POST {{$dotenv host}}/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin3@babelcoder.com",
  "password": "password"
}

###

POST {{$dotenv host}}/auth/login
Content-Type: application/json

{
  "email": "admin3@babelcoder.com",
  "password": "password"
}
###

POST {{$dotenv host}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{$dotenv refreshToken}}"
}

###

GET {{$dotenv host}}/auth/profile
Authorization: Bearer {{$dotenv accessToken}}

###

PATCH {{$dotenv host}}/auth/profile
Authorization: Bearer {{$dotenv accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Admin3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[houseNumber]"

111/11
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[village]"

Product 1 Desc
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[road]"

Petchaburi
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[district]"

Ratchatawee
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[province]"

Mukkasan
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address[postalCode]"

10240
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="avatar.png"
Content-Type: image/png

< ./http/data/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
DELETE {{$dotenv host}}/auth/logout
Authorization: Bearer {{$dotenv accessToken}}

###

POST {{$dotenv host}}/products
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

My Product
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

2000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="desc"

Product 1 Desc
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryIds[]"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="product.png"
Content-Type: image/png

< ./http/data/product.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

PATCH {{$dotenv host}}/products/101
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Product 1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="desc"

Product 1 Desc
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryIds[]"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="product.png"
Content-Type: image/png

< ./http/data/product.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET {{$dotenv host}}/products?page=3&limit=5


###

GET {{$dotenv host}}/products/2

###

DELETE {{$dotenv host}}/products/99

###

GET {{$dotenv host}}/categories

###

GET {{$dotenv host}}/categories/1

###

POST {{$dotenv host}}/categories
Content-Type: application/json
Authorization: Bearer {{$dotenv accessToken}}

{
  "name": "MyCat11",
  "desc": "MyCat11-Desc"
}

###

PATCH {{$dotenv host}}/categories/21
Content-Type: application/json

{
  "name": "MyCat21",
  "desc": "MyCat-Desc21"
}

###

DELETE {{$dotenv host}}/categories/23
Authorization: Bearer {{$dotenv accessToken}}

###

POST {{$dotenv host}}/orders
Content-Type: application/json
Authorization: Bearer {{$dotenv accessToken}}

{
  "items": [
    {
      "productId": 1,
      "quantity": 2,
      "price": 100
    },
    {
      "productId": 2,
      "quantity": 3,
      "price": 1000
    }
  ]
}

###

GET {{$dotenv host}}/orders
Authorization: Bearer {{$dotenv accessToken}}

###

GET {{$dotenv host}}/orders/1001
Authorization: Bearer {{$dotenv accessToken}}